# Generated by Django 6.0.3 on 2026-03-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10, unique=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("double", "Double"),
                            ("twin", "Twin"),
                            ("suite", "Suite"),
                            ("deluxe", "Deluxe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("floor", models.IntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("maintenance", "Maintenance"),
                            ("cleaning", "Cleaning"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("capacity", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["floor", "number"],
            },
        ),
    ]
