from datetime import timedelta
from pathlib import Path
import os
import dj_database_url

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'drf_spectacular',

    'apps.accounts',
    'apps.rooms',
    'apps.customers',
    'apps.reservations',
    'apps.billing',
    'apps.food',
    'apps.housekeeping',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # ← add this
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL")
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Allow Angular to talk to Django
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
]

# JWT Authentication
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

AUTH_USER_MODEL = 'accounts.User'

SPECTACULAR_SETTINGS = {
    'TITLE': 'Hotel Management System API',
    'DESCRIPTION': 'API for the Hotel ERP system',
    'VERSION': '1.0.0',
    'SECURITY': [{'bearerAuth': []}],
    'COMPONENTS': {
        'securitySchemes': {
            'bearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # ← add this line
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}


JAZZMIN_SETTINGS = {
    # ── Branding ──────────────────────────────────
    "site_title":        "Aurum Admin",
    "site_header":       "Aurum Hotel",
    "site_brand":        "⬡ AURUM",
    "site_logo":         None,
    "welcome_sign":      "Welcome to the Aurum Hotel Management System",
    "copyright":         "Aurum Hotel ERP",

    # ── Top Menu ──────────────────────────────────
    "topmenu_links": [
        {
            "name":  "View Site",
            "url":   "http://localhost:4200",
            "new_window": True
        },
        {
            "name":  "API Docs",
            "url":   "/api/docs/",
            "new_window": True
        },
    ],

    # ── User Menu ─────────────────────────────────
    "usermenu_links": [
        {
            "name":        "API Docs",
            "url":         "/api/docs/",
            "new_window":  True,
            "icon":        "fas fa-book"
        },
    ],

    # ── Sidebar ───────────────────────────────────
    "show_sidebar":            True,
    "navigation_expanded":     True,
    "hide_apps":               [],
    "hide_models":             [],

    # ── Icons ─────────────────────────────────────
    "icons": {
        "auth":                      "fas fa-users-cog",
        "accounts.user":             "fas fa-user-tie",
        "rooms.room":                "fas fa-bed",
        "customers.customer":        "fas fa-user-friends",
        "reservations.booking":      "fas fa-calendar-check",
        "billing.invoice":           "fas fa-file-invoice-dollar",
        "food.menuitem":             "fas fa-utensils",
        "food.foodorder":            "fas fa-concierge-bell",
        "food.orderitem":            "fas fa-list",
        "housekeeping.cleaningtask": "fas fa-broom",
        "housekeeping.hygienereport":"fas fa-clipboard-check",
        "housekeeping.supplylog":    "fas fa-boxes",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # ── UI Tweaks ─────────────────────────────────
    "related_modal_active":       True,
    "custom_js":                  None,
    "use_google_fonts_cdn":       True,
    "show_ui_builder":            False,

    # ── Search ────────────────────────────────────
    "search_model": ["accounts.user", "customers.customer", "rooms.room"],

    # ── Change view ───────────────────────────────
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text":    False,
    "footer_small_text":    False,
    "body_small_text":      False,
    "brand_small_text":     False,
    "brand_colour":         "navbar-dark",
    "accent":               "accent-warning",
    "navbar":               "navbar-dark",
    "no_navbar_border":     True,
    "navbar_fixed":         True,
    "layout_boxed":         False,
    "footer_fixed":         False,
    "sidebar_fixed":        True,
    "sidebar":              "sidebar-dark-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme":                "darkly",
    "default_theme_mode" : 'dark',
    "button_classes": {
        "primary":   "btn-primary",
        "secondary": "btn-secondary",
        "info":      "btn-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },
}